# Generated by Django 4.2 on 2025-02-24 08:25

from django.db import migrations, models
import resume_uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[resume_uploads.models.validate_extension]),
        ),
    ]
